# Generated by Django 4.0 on 2021-12-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previsao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previsao',
            old_name='_id',
            new_name='id',
        ),
    ]
